export const GET_MENU_REQUEST = "GET_MENU_REQUEST" 
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS"
export const GET_MENU_ERROR = "GET_MENU_ERROR"

export const ADD_MENU_REQUEST = "ADD_MENU_REQUEST" 
export const ADD_MENU_SUCCESS = " ADD_MENU_SUCCESS"
export const ADD_MENU_ERROR = "ADD_MENU_ERROR"

export const DELETE_MENU_REQUEST = "DELETE_MENU_REQUEST" 
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS"
export const DELETE_MENU_ERROR = "DELETE_MENU_ERROR"

export const UPDATE_MENU_REQUEST = "UPDATE_MENU_REQUEST" 
export const UPDATE_MENU_SUCCESS = "UPDATE_MENU_SUCCESS"
export const UPDATE_MENU_ERROR = "UPDATE_MENU_ERROR"

export const GET_SINGLE_MENU = "GET_SINGLE_MENU";
